version: 1.0.{build}
image: Visual Studio 2015

clone_script:
- git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- git checkout -qf %APPVEYOR_REPO_COMMIT%

environment:
  VIRUSTOTAL_API_KEY:
    secure: 6VgzXytQY3l+cUPsvEuhSqu/E8JqJQPOK1Kh7mViN0SJ1M3ZHzteSpC56q3HbWXSUCAhk7ynS0BVBYDWVxi5XSXdRLCRiWaAgG7zeNoNk6Q=

build_script:
- C:/msys64/usr/bin/wget.exe -nv "https://downloads.dlang.org/releases/2.x/2.108.1/dmd-2.108.1.exe"
- start /wait dmd-2.108.1.exe /S
- C:/msys64/usr/bin/wget.exe -nv https://github.com/datadiode/mingw-w64-libs/releases/download/v8.0.2/mingw-w64-libs-v8.0.2.exe
- start /wait mingw-w64-libs-v8.0.2.exe /autoextract
- C:/msys64/usr/bin/wget.exe -nv "https://github.com/zpaq/zpaq/releases/download/7.15/zpaq715.zip"
- 7z x -ooutput zpaq715.zip
- build_script.bat

after_build:
- output\MakeSetup.bat
- bash.exe %APPVEYOR_BUILD_FOLDER%\virustotal_upload %APPVEYOR_BUILD_FOLDER%\output\FESetup.exe %APPVEYOR_BUILD_FOLDER%\output\virustotal_report.jsn

artifacts:
- path: output\FESetup.exe
- path: output\FESetup.zpaq
- path: output\virustotal_report.jsn
