#define IDI_SETUP1                      101
#define IDD_TEMPLATE                    102
#define IDB_INTRO                       103
#define IDD_SPLASH                      104
#define IDD_PATH                        105
#define IDD_PROGRESS                    106
#define IDD_FINISHED                    107
#define IDB_ARROW                       110
#define IDR_MENU1                       113
#define IDC_HAND1                       123
#define IDB_BITMAP1                     126
#define IDD_ABOUT                       129
#define IDR_BIN1                        134
#define IDC_BACK                        1000
#define IDC_EXTRACTPATH                 1002
#define IDC_NEXT                        1003
#define IDC_GLYPHBROWSE                 1004
#define IDC_CANCEL                      1005
#define IDC_PROGRESSBAR                 1007
#define IDC_INTROBANNER                 1009
#define IDC_URL                         1010
#define IDC_OPENFOLDER                  1011
#define IDC_BOTTOMFRAME                 1013
#define IDC_AUTOCREATEDIR               1014
#define IDC_BANNER                      1015
#define IDC_TEXT                        1016
#define IDC_SUBBANNER                   1017
#define IDC_STATUS                      1018
#define IDC_WHITEBANNER                 1019
#define IDC_TITLE                       1021
#define IDC_TOPFRAME                    1022
#define IDM_ABOUT                       40001
